interface logging {
    variant request {
        log(string),
    }

    variant response {
        log(result<_, string>),
    }
}

world logging-nick-dot-hypr-v0 {
    import logging;
    include process-v1;
}
